'use client'

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/globals.sass";
import SideBar from "@/components/SideBar";
import { QueryClient, QueryClientProvider } from 'react-query';
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const [queryClient] = useState(() => new QueryClient({
    defaultOptions: {
      queries: {
        refetchOnWindowFocus: false, // default: true
      },
    },
  }));
  return (
    <QueryClientProvider client={queryClient}>
      <html lang="en" suppressHydrationWarning={true}>
        <body className={`flex gap-5 ${inter.className}`}>
          <SideBar />
          {children}
        </body>
      </html>
    </QueryClientProvider>
  );
}
